supabase-community/postgres-language-server

.github/ISSUE_TEMPLATE/config.yml

Override [the organization-level configuration](https://github.com/supabase/supabase/discussions/categories/feature-requests) which redirects Feature Requests to the main `supabase/supabase` discussions page
This may be unwanted, according to this comment by @kiwicopple:
- https://github.com/orgs/supabase/discussions/16286#discussioncomment-6657204

Override config from supabase/.github

---

.gitmodules

I was unable to checkout the submodule without the new https path.

fix: use https path for libpg_query submodule

---

crates/codegen/src/get_node_properties.rs
crates/parser/src/codegen.rs

Feature: try to add support for "create domain" statement as requested in #51
Parser panics:
```sh
could not find node for token Token { kind: Create, text: "CREATE", span: 0..6, token_type: ReservedKeyword } at depth 1
```
Parser returns:
```sh
CreateDomainStmt@0..37
Create@0..6 "CREATE"
Whitespace@6..7 " "
DomainP@7..13 "DOMAIN"
Whitespace@13..14 " "
Ident@14..28 "us_postal_code"
Whitespace@28..29 " "
As@29..31 "AS"
Whitespace@31..32 " "
TypeName@32..36
TextP@32..36 "TEXT"
Ascii59@36..37 ";"
```
Not sure of what exactly should go in the `CreateDomainStmt` branch, but I have tried with these variations and it worked:
```sql
CREATE DOMAIN name [ AS ] data_type [ constraint [ ... ] ]
```

add support for parsing "create domain" statement

---

crates/codegen/src/get_node_properties.rs
crates/parser/src/codegen.rs

In the continuation of #61 & #51. Ultimately, being able to parse most of the DDL statements would be nice
Parser panics:
```sh
could not find node for token Token { kind: Create, text: "CREATE", span: 0..6, token_type: ReservedKeyword } at depth 1
```
Parser returns:
```rust
CreateSchemaStmt(
CreateSchemaStmt {
schemaname: "test",
authrole: Some(
RoleSpec {
roletype: RolespecCstring,
rolename: "joe",
location: 47,
},
),
schema_elts: [],
if_not_exists: true,
},
),
```
Add any other context or screenshots.

feat: support "create schema"

---

Cargo.toml
crates/codegen/src/parser.rs
crates/pg_query_proto_parser/src/proto_parser.rs
crates/postgres_lsp/src/main.rs
rust-toolchain.toml

Fixes various warnings encountered when trying to run the project
- testing requires `cargo +nightly test`
- warnings with `cargo check`
- `parser` lib cannot be used a `dependencies` (proto file path is relative)
- testing with `cargo test`
- no warnings
- `parser` lib can be used a `dependencies`
This PR can be split into multiple PRs if you see fit @psteinroe

minor fixes for easier contrib

---

crates/codegen/src/get_node_properties.rs
crates/parser/src/codegen.rs

Follow-up for #63, #51
Parser panics
Parser returns:
```rust
ViewStmt(
ViewStmt {
view: Some(
RangeVar {
catalogname: "",
schemaname: "",
relname: "comedies",
inh: true,
relpersistence: "t",
alias: None,
location: 33,
},
),
aliases: [],
query: Some(
Node {
node: Some(
SelectStmt(
SelectStmt {
distinct_clause: [],
into_clause: None,
target_list: [
Node {
node: Some(
ResTarget(
ResTarget {
name: "",
indirection: [],
val: Some(
Node {
node: Some(
ColumnRef(
ColumnRef {
fields: [
Node {
node: Some(
AStar(
AStar,
),
),
},
],
location: 52,
},
),
),
},
),
location: 52,
},
),
),
},
],
from_clause: [
Node {
node: Some(
RangeVar(
RangeVar {
catalogname: "",
schemaname: "",
relname: "films",
inh: true,
relpersistence: "p",
alias: None,
location: 59,
},
),
),
},
],
where_clause: None,
group_clause: …
```

feat: support "create view" with relpersistence

---

crates/codegen/src/get_node_properties.rs
crates/parser/src/codegen.rs
crates/parser/tests/data/statements/valid/0037.sql

feat: support `CreateEnumStmt`
Parser panics
```rust
[2023-12-13T14:27:17Z DEBUG parser::codegen::tests] pg_query_root: Some(
CreateEnumStmt(
CreateEnumStmt {
type_name: [
Node {
node: Some(
String(
String {
sval: "status",
},
),
),
},
],
vals: [
Node {
node: Some(
String(
String {
sval: "open",
},
),
),
},
Node {
node: Some(
String(
String {
sval: "closed",
},
),
),
},
],
},
),
)
```
Add any other context or screenshots.

feat: support `CreateEnumStmt`

---

crates/codegen/src/get_node_properties.rs
crates/codegen/src/parser.rs

Leverage the fact that most of the `match`ed node properties has a corresponding enum in the `protobuf` definition
Matching is done with raw `i32`
Matching is done with associated enum
This should improve readability and let us omit some comments since we can now jump to the `protobuf` definition

refactor(codegen): use protobuf enums

---

crates/codegen/src/get_node_properties.rs
crates/parser/src/codegen.rs
crates/parser/tests/data/statements/valid/0046.sql

add support for `create range`
panics
parser returns
<details>
<summary>View log</summary>
```rust
CreateRangeStmt {
type_name: [
Node {
node: Some(
String(
String {
sval: "type1",
},
),
),
},
],
params: [
Node {
node: Some(
DefElem(
DefElem {
defnamespace: "",
defname: "subtype",
arg: Some(
Node {
node: Some(
TypeName(
TypeName {
names: [
Node {
node: Some(
String(
String {
sval: "int4",
},
),
),
},
],
type_oid: 0,
setof: false,
pct_type: false,
typmods: [],
typemod: -1,
array_bounds: [],
location: 38,
},
),
),
},
),
defaction: DefelemUnspec,
location: 28,
},
),
),
},
],
}
```
</details>
Add any other context or screenshots.

feat: add support for create range

---

crates/codegen/src/get_node_properties.rs
crates/parser/src/codegen.rs
crates/parser/tests/data/statements/valid/0051.sql

add support for `create index`
panics
<s>parser panics for index with `using btree` (the default) - it works if omitted</s>
parser returns with 5e1ef7b61b38f704b7f4f2af56c441ae9ebcdcfa, but as a side-note `Using` is always pushed
<details>
<summary>View log</summary>
```rust
IndexStmt {
idxname: "title_idx",
relation: Some(
RangeVar {
catalogname: "",
schemaname: "",
relname: "films",
inh: true,
relpersistence: "p",
alias: None,
location: 33,
},
),
access_method: "btree",
table_space: "",
index_params: [
Node {
node: Some(
IndexElem(
IndexElem {
name: "title",
expr: None,
indexcolname: "",
collation: [],
opclass: [],
opclassopts: [],
ordering: SortbyDefault,
nulls_ordering: SortbyNullsDefault,
},
),
),
},
],
index_including_params: [],
options: [],
where_clause: None,
exclude_op_names: …
```

feat: add support for create index

---

crates/codegen/src/get_node_properties.rs
crates/codegen/src/get_nodes.rs
crates/parser/src/parse/libpg_query_node.rs
crates/parser/tests/data/statements/valid/0039.sql

adds support for `CREATE AGGREGATE`
panics
still panics for aggregates with `ORDER BY`
follow-up for #69

feat: pass `parent` to `get_node_properties` and add support for create aggregate with order by

---

.github/actions/setup-monorepo/action.yml
.github/workflows/ci.yml
xtask/src/flags.rs
xtask/src/install.rs
xtask/src/main.rs

Add caching to speedup CI time
CI takes time due to `build-dependencies` like `libpg_query`
CI uses [rust-cache](https://github.com/Swatinem/rust-cache) to improve compile time, a sample before / after: `3m 22s -> 45s`
other minor fixes included:
- `+nightly` is implied by the `rust-toolchain` file
- `cargo check` was added a new step
- `cargo fmt` was ran (but not checked in CI)
To my surprise [actions-rs/toolchain](https://github.com/actions-rs/toolchain) was recently archived, but this can be reverted if not required

perf(ci): use cache

---

crates/parser/src/parse/statement.rs
crates/parser/src/parser.rs

follow-up for #85
properly handle BEGIN...END similar to how sub statements are handled.
sample that now passes:
```
CREATE PROCEDURE insert_data(a integer, b integer) LANGUAGE SQL BEGIN ATOMIC INSERT INTO tbl VALUES (a); INSERT INTO tbl VALUES (b); END;
```

fix: handle BEGIN...END in statment_parser

---

crates/codegen/src/get_node_properties.rs
crates/parser/src/codegen.rs
crates/parser/tests/data/statements/valid/0045.sql

add support for `create operator`
panics
parser returns
<details>
<summary>View log</summary>
```rust
DefineStmt {
kind: ObjectOperator,
oldstyle: false,
defnames: [
Node {
node: Some(
String(
String {
sval: "+",
},
),
),
},
],
args: [],
definition: [
Node {
node: Some(
DefElem(
DefElem {
defnamespace: "",
defname: "procedure",
arg: Some(
Node {
node: Some(
TypeName(
TypeName {
names: [
Node {
node: Some(
String(
String {
sval: "plusfunc",
},
),
),
},
],
type_oid: 0,
setof: false,
pct_type: false,
typmods: [],
typemod: -1,
array_bounds: [],
location: 48,
},
),
),
},
),
defaction: DefelemUnspec,
location: 36,
},
),
),
},
Node {
node: Some(
DefElem(
DefElem {
defnamespace: "",
defname: "leftarg",
arg: Some(
Node {
node: Some(
TypeName(
TypeName {
names: [
Node {
node: Some(
String(
String { …
```

feat: add support for create operator

---

crates/codegen/src/get_node_properties.rs
crates/parser/src/codegen.rs
crates/parser/tests/data/statements/valid/0052.sql

add support for `create procedure`
panics
<s>parser returns</s>
`test_create_procedure` passes but parser produces incorrect tree
<details>
<summary>View log</summary>
```rust
CreateFunctionStmt {
is_procedure: true,
replace: false,
funcname: [
Node {
node: Some(
String(
String {
sval: "insert_data",
},
),
),
},
],
parameters: [
Node {
node: Some(
FunctionParameter(
FunctionParameter {
name: "a",
arg_type: Some(
TypeName {
names: [
Node {
node: Some(
String(
String {
sval: "pg_catalog",
},
),
),
},
Node {
node: Some(
String(
String {
sval: "int4",
},
),
),
},
],
type_oid: 0,
setof: false,
pct_type: false,
typmods: [],
typemod: -1,
array_bounds: [],
location: 31,
},
),
mode: FuncParamDefault,
defexpr: None,
},
),
),
},
],
return_type: None,
options: [
Node {
node: Some(
DefElem(
DefElem { …
```

feat: add support for create procedure

---

crates/codegen/src/get_location.rs
crates/codegen/src/get_node_properties.rs
crates/parser/tests/data/statements/valid/0053.sql
crates/parser/tests/snapshots/statements/valid/0049@2.snap
crates/parser/tests/snapshots/statements/valid/0053@1.snap
crates/parser/tests/snapshots/statements/valid/0053@2.snap
crates/parser/tests/snapshots/statements/valid/0053@3.snap
crates/parser/tests/snapshots/statements/valid/0053@4.snap
crates/parser/tests/snapshots/statements/valid/0053@5.snap
crates/parser/tests/snapshots/statements/valid/0053@6.snap
crates/parser/tests/snapshots/statements/valid/0053@7.snap

fix: location and add support for create publication

---

crates/codegen/src/get_node_properties.rs
crates/parser/src/parse/statement.rs
crates/parser/tests/data/statements/valid/0044.sql
crates/parser/tests/data/statements/valid/0055.sql
crates/parser/tests/snapshots/statements/valid/0044@5.snap
crates/parser/tests/snapshots/statements/valid/0055@1.snap
crates/parser/tests/snapshots/statements/valid/0055@2.snap

add support for combining queries
ref: https://www.postgresql.org/docs/current/queries-union.html
also fixed some minor bugs with `ViewStmt`
does parse individual statements 
parses them as a single combined statement.

feat: add support for combining queries

---

crates/codegen/src/get_node_properties.rs
crates/parser/src/codegen.rs
crates/parser/tests/data/statements/valid/0056.sql
crates/parser/tests/snapshots/statements/valid/0056@1.snap
crates/parser/tests/snapshots/statements/valid/0056@2.snap

Adds support for [create transform](https://www.postgresql.org/docs/current/sql-createtransform.html)
LSP exits with code 101 upon encountering `create transform`
Handles `create transform` queries
N/A

feat: support `create transform`

---

crates/codegen/src/get_node_properties.rs
crates/parser/tests/data/statements/valid/0043.sql
crates/parser/tests/snapshots/statements/valid/0043@1.snap
crates/parser/tests/snapshots/statements/valid/0043@10.snap
crates/parser/tests/snapshots/statements/valid/0043@11.snap
crates/parser/tests/snapshots/statements/valid/0043@2.snap
crates/parser/tests/snapshots/statements/valid/0043@3.snap
crates/parser/tests/snapshots/statements/valid/0043@4.snap
crates/parser/tests/snapshots/statements/valid/0043@5.snap
crates/parser/tests/snapshots/statements/valid/0043@6.snap
crates/parser/tests/snapshots/statements/valid/0043@7.snap
crates/parser/tests/snapshots/statements/valid/0043@8.snap
crates/parser/tests/snapshots/statements/valid/0043@9.snap

add support for `create table like`
panics
parser returns
Last batch of PRs before pulling in the `postgres` regression tests

feat: add support for create table like

---

README.md

[Docs]: Installation guide for CodeSpaces

---

crates/parser/tests/data/statements/valid/0043.sql
crates/parser/tests/snapshots/statements/valid/0043@3.snap
crates/parser/tests/snapshots/statements/valid/0043@4.snap

add tests for `create table`
statements in `parse.stmts` is empty (see snapshots)
parser returns CST and statements
more of a reproduction case instead of a real PR cc @psteinroe

test: extend support for create table

---

crates/codegen/src/get_node_properties.rs
crates/parser/tests/data/statements/valid/0043.sql
crates/parser/tests/snapshots/statements/valid/0043@2.snap

add support for "some" `typename`
parser panics
parser returns
as I understands it, the case that causes panics are: 
- multi-word type name, eg: `timestamp with time zone`
- and interval options, eg: `hour to second(3)`
single-word type name, looks ok but I will have to double-check. cc @psteinroe

feat: add support for type name

---

crates/codegen/src/get_node_properties.rs
crates/parser/tests/data/statements/valid/0043.sql
crates/parser/tests/snapshots/statements/valid/0043@7.snap
crates/parser/tests/snapshots/statements/valid/0043@8.snap

add tests for `create table as`
parser collects errors after `as` keyword (see snapshots)
parser returns without errors
same here, reproduction case cc @psteinroe

test: add support for create table as

---

crates/codegen/src/get_node_properties.rs

add missing `interval` fields from from https://www.postgresql.org/docs/16/datatype-datetime.html
parser panics
parser returns
as in #106, "multi-word" interval fields are required, eg. this query:
```sql
CREATE TABLE IF NOT EXISTS distributors (len interval hour to second(3));
```
expect this tokens:
<s>tokens.push(TokenProperty::from(Token::HourP));</s>
```rust
tokens.push(TokenProperty::from(Token::To));
tokens.push(TokenProperty::from(Token::SecondP));
```

feat: add interval fields

---

crates/parser/src/parse/libpg_query_node.rs

copy data types from https://www.postgresql.org/docs/current/datatype.html
missing aliases
added aliases
as per https://github.com/supabase/postgres_lsp/pull/109#discussion_r1445248208, multi-word type names (eg. `timestamp with time zone`) requires a larger change

feat: add datatypes aliases

---

editors/code/package-lock.json

This PR bumps an npm package to fix this dependabot alert: https://github.com/supabase/postgres_lsp/security/dependabot/3.

fix a dependabot alert

---

crates/codegen/src/get_node_properties.rs
crates/parser/src/codegen.rs

add support for `SELECT .. ORDER BY ...`

---

Cargo.lock

Fix this dependabot alert: https://github.com/supabase/postgres_lsp/security/dependabot/4

bump shlex to fix a dependabot alert

---

crates/codegen/src/get_node_properties.rs
crates/parser/src/codegen.rs
crates/parser/src/parse/statement_start.rs
crates/parser/tests/data/statements/valid/0046.sql
crates/parser/tests/snapshots/statements/valid/0046@1.snap
crates/parser/tests/snapshots/statements/valid/0046@2.snap
crates/parser/tests/snapshots/statements/valid/0046@3.snap
crates/parser/tests/snapshots/statements/valid/0046@7.snap
crates/parser/tests/snapshots/statements/valid/0046@8.snap

add support for object type in `DefineStmt`
--
--
while working on this, I realized there is a few statements that have an AST mismatch from `pg_query`:
https://github.com/search?q=repo%3Asupabase%2Fpostgres_lsp+%22stmts%3A+%5B%5D%2C%22&type=code
with either: no AST (sometimes expected) or AST with wrong nodes (eg. for `create procedure`)
@psteinroe lmk if i should try to investigate these ones next

fix: support `create type`

---

crates/pg_schema_cache/src/lib.rs
crates/pg_schema_cache/src/schema_cache.rs
crates/pg_schema_cache/src/versions.rs

Adds the postgres version in the schema cache using SQL from the `pg-meta` library.

adds postgres version to the schema cache.

---

editors/code/.prettierrc.js
editors/code/src/main.ts
xtask/src/install.rs

When we install and use the VS Code extension, we're now installing the correct crate and running the correct binary.
I also added already-in-use, non-default settings to the `.prettierrc.js` file, so that the diff is more readable.
Running `cargo xtask install` fails because it's looking for a `postgres_lsp` crate; there is none. The crate is called `pg_lsp`.
Starting the VSCode extension fails because it tries to execute the `postgres_lsp` binary; it's called `pglsp`. 
We're installing the correct crate and executing the correct binary. 
It's working now 🥳🥳🥳:

fix(vscode): extension command, server crate path

---

Cargo.lock
Cargo.toml
crates/pg_base_db/Cargo.toml
crates/pg_base_db/src/change.rs
crates/pg_base_db/src/document.rs
crates/pg_base_db/src/lib.rs
crates/pg_fs/Cargo.toml
crates/pg_fs/src/dir.rs
crates/pg_fs/src/lib.rs
crates/pg_fs/src/path.rs
crates/pg_lsp/Cargo.toml
crates/pg_lsp/src/utils.rs
crates/pg_lsp/src/utils/line_index_ext.rs
crates/pg_workspace/Cargo.toml
crates/pg_workspace/src/lib.rs

first pr towards a new Workspace create. reason for this change is that
we will need some sort of fs crate for the cli eg to setup the socket.
this is what ensure_cache_dir is for.

refactor: move PgLspPath into pg_fs crate

---

crates/pg_lsp/src/client/client_config_opts.rs
crates/pg_lsp/src/db_connection.rs
crates/pg_lsp/src/server.rs
crates/pg_lsp/src/session.rs
docker-compose.yml
editors/code/package.json

I noticed that the `workspace/configuration` flow wasn't properly supported – we only requested the config when receiving a `workspace/didChangeConfiguration` request (which is the old flow).
TBH I don't think merging this is even necessary, since we'll search for and parse a `pglsp.toml` file [once this is merged](https://github.com/supabase-community/postgres_lsp/pull/147) which is probably the better approach. :)

fix(pglsp): properly set up workspace/configuration flow

---

crates/pg_lexer/src/lib.rs

Bug fix.
`whitespace_tokens` adds the wrong `kind` attribute for `Token` when the regex has captured a tab (`Newline`)
It uses the correct `kind` attribute, `Tab`.

fix: small bug in whitespace_tokens, added a few tests for such bugs.

---

crates/pg_syntax/tests/pg_syntax_tests.rs

Small test function optimization.
`SKIPPED_REGRESS_TESTS` are vectorized on every loop (inside two loops).
The vector is defined before the loops.

avoid building skipped tests vector in every loop

---

editors/code/src/main.ts
xtask/src/install.rs

The VSCode extension now uses the `pg_cli` 🙌

fix(vscode-ext.): use pg_cli 

---

crates/pg_lsp/src/handlers/text_document.rs
crates/pg_workspace/src/workspace/server/change.rs

trying to fix a bug where all statements are deleted when deleting at eof. and when modifying a statement.
fixes:
- using line index of old document during change instead of new
- gracefully handling changes that are out of bounds of the current content. no idea why these are sent, but they are sometimes. instead of investigating where they come from I just added a check to ensure a TextRange is always valid.
- change_range in ModifiedStatement was not adapted to the range of the statement, causing a crash and invalid diagnostics ranges when modifying within a statement.  
ready now. no idea why I didn't finish it earlier. I was sure I already had 😅

fix: change at eof

---

Cargo.lock
crates/pg_cli/Cargo.toml
crates/pg_cli/src/commands/check.rs
crates/pg_cli/src/commands/mod.rs
crates/pg_cli/src/execute/traverse.rs
crates/pg_cli/src/lib.rs
crates/pg_configuration/src/database.rs
crates/pg_configuration/src/files.rs
crates/pg_configuration/src/lib.rs
crates/pg_configuration/src/migrations.rs
crates/pg_workspace/Cargo.toml
crates/pg_workspace/src/settings.rs
crates/pg_workspace/src/workspace/server.rs
crates/pg_workspace/src/workspace/server/migration.rs
pglsp.toml

goal of this pr is to gear the cli towards the use case we want to support initially: running a check command on migration file(s).
after a discussion with @juleswritescode, this is the plan:
We will have one single `pgtoools check` command. by default, it will scan everything for sql files and lint it. it can be filtered by path, e.g. `pgtools check supabase/migrations` to just lint the migration directory. We will have a `migrations-dir` config option that will enable extra filtering features for files within the directory, primarily `--after` and maybe `--last-nth`. Furthermore, we will also have `--staged` and `--changed` to easily lint just the relevant migrations in a CI environment or a pre-commit hook. The existing `--include` and `--exclude` filters will continue to work. 
To …

cli ergonomics

---

crates/pg_lexer/src/lib.rs
crates/pg_workspace/src/settings.rs
crates/pg_workspace/src/workspace/server.rs

fixes #184 
also using `TextSize` now. but we might want to revisit the lexer at some point because I dont think we should store the text in the tokens anymore.

fix: handle unicode in lexer

---

README.md
crates/pg_lexer/README.md
crates/pg_lexer_codegen/README.md

I tried to understand how the `pg_lexer` crate and its interaction with `libpg_query` works and thought it would be a good idea to write it down. 
Please check if I understand it correctly.

docs(pg_lexer): add some info about libpg_query and SyntaxKind

---

crates/pg_analyser/CONTRIBUTING.md
crates/pg_analyser/src/lint/safety.rs
crates/pg_analyser/src/lint/safety/ban_drop_column.rs
crates/pg_analyser/src/lint/safety/ban_drop_not_null.rs
crates/pg_analyser/src/options.rs
crates/pg_configuration/src/analyser/linter/rules.rs
crates/pg_diagnostics_categories/src/categories.rs
pglsp.toml

I tried adding a new lint rule, but the `just gen-lint` script fails:
I can't see a syntax error in this statement:
`alter table users alter column email drop not null;` 
so maybe something is broken?

feat(analyser): banDropNotNull rule

---

.github/workflows/pull_request.yml

runs `lint --fix` in the workflow and checks for any diffs. this should reduce unrelated changes in prs.

fix: check for lint fix in workflow

---

docs/rule_sources.md
docs/rules.md
docs/rules/ban-drop-table.md
docs/schemas/0.0.0/schema.json
docs/schemas/latest/schema.json

I just ran `cargo run -p docs_codegen`.

docs: add ban-drop-table docs

---

crates/pglt_lsp/src/session.rs
crates/pglt_workspace/src/workspace/server/schema_cache_manager.rs

fixes our bug from last night. the issue was actually that the entire server went into a lock when loading the `SchemaCache` for auto-completion, because we did not release the read lock on `inner` before acquiring the write lock. I wonder how we could write a test for these kind of issues 🤔 maybe some kind of simulation e2e test where we actually start the server and start to send some commands and then stop it again. 
also removed some spammy logs.

fix(pglt_workspace): lock

---

Cargo.lock
crates/pglt_lsp/Cargo.toml
crates/pglt_lsp/tests/server.rs

adds a basic lifecycle test to the lsp server. will expand on it later. maybe we can even have a "recording" of the users actions via logs, parse these recordings and replay them.

chore(pglt_lsp): add lifecycle test

---

docs/checking_migrations.md
docs/index.md

We should also add a section for --since and --changes

docs: add short guide for migrations

---

crates/pglt_completions/src/providers/columns.rs
crates/pglt_completions/src/providers/functions.rs
crates/pglt_completions/src/providers/tables.rs
crates/pglt_lsp/tests/server.rs
crates/pglt_workspace/src/workspace/server.rs
crates/pglt_workspace/src/workspace/server/change.rs

after some forth and back yesterday and a crash when starting to complete after a change I realised I am big idiot because not emitting whitespaces will result in an invalid tree sitter tree… 🥲 so yeah, we just emit them now. also added an e2e test for completions.
also
- removed changed statements because we do not use them and they will jus grow over time 
- my format-on-write did minor changes to the sql in tests

fix: emit whitespace changes after all

---

docs/codegen/src/default_configuration.rs
docs/index.md

chore: fix bug in codegen

---

crates/pgt_workspace/src/workspace/server/change.rs
justfile

tried to repro something but without success. still doesnt hurt to keep the test.

chore: add test

---

docs/index.md

Feel free to edit this. The goal is to create a clearer logical flow:
- overview
- install
- configure
- use
previously the installation instructions are a bit scattered

regrouping installation options

---

.github/workflows/deploy_docs.yml

fixes #284 
this should help a bit until we setup nightly releases or versioned docs.

chore: only deploy docs on release

---

docs/index.md

Docs update fixing link to VSCode Marketplace
link 404s
Links to VSCode extension page
none

Fix link to VSCode Marketplace

---

.github/workflows/release.yml

fixes #279 
I *think* `—bumped-version` returns the same version as the `bump` we call later but without actually bumping. let me know if this is correct @juleswritescode.
docs: https://git-cliff.org/docs/usage/bump-version#get-version

fix: version

---

crates/pgt_lsp/tests/server.rs
crates/pgt_workspace/src/workspace/server/change.rs

closes #281 
we need to use byte indices

fix: use byte indices

---

crates/pgt_lsp/src/handlers/code_actions.rs
crates/pgt_typecheck/src/lib.rs

I've been through many iterations but this seems to be the simplest.
We use a dedicated connection for the `prepare` statement and close it on drop. This will clear all the prepared statements for that session. `sqlx` itself doesn't cache anything when using `prepare`. If we worry about performance overhead, I suggest we a) use sqlx cache via `prepare_with` and b) debounce the publishing of diagnostics again 👍

fix: execute statement reliable

---

crates/pgt_workspace/src/workspace/server.rs
crates/pgt_workspace/src/workspace/server/migration.rs

fix: support non timestamp but numeric migrations

---

crates/pgt_lsp/tests/server.rs
crates/pgt_workspace/src/settings.rs
crates/pgt_workspace/src/workspace/server/change.rs

fix: make sure range is correct for eof deletions

---

.github/workflows/publish.reusable.yml
.github/workflows/pull_request.yml
.github/workflows/release.yml

Downgrades runners wherever we need to build the binary.
When I checked with Docker, Ubuntu-22.04 had glibc version 2.35, so that should help #280

fix: downgrade runners

---

crates/pgt_lexer/src/lib.rs
crates/pgt_statement_splitter/src/lib.rs

fix: c-style comments

---

Cargo.lock
crates/pgt_workspace/Cargo.toml
crates/pgt_workspace/src/workspace/server.rs
crates/pgt_workspace/src/workspace/server/annotation.rs
crates/pgt_workspace/src/workspace/server/change.rs
crates/pgt_workspace/src/workspace/server/parsed_document.rs
crates/pgt_workspace/src/workspace/server/statement_identifier.rs

adds a very simple `Annotation` service. the idea here is to annotate a statement using the lexed tokens. right now, it just returns whether or not the statement ends with a semicolon. in near future, I will also parse comments and their content so we can do #304, e.g. 
```sql
-- postgrestools disable-next-line my-rule
select 1;
```
but to do that I will first need to adapt the splitter so that comments like that are included in the statement range :) 
also replaced the `root_id` fn with `From` implementations

feat: annotations

---

Cargo.lock
crates/pgt_completions/Cargo.toml
crates/pgt_completions/benches/sanitization.rs
crates/pgt_completions/src/complete.rs
crates/pgt_completions/src/context.rs
crates/pgt_completions/src/lib.rs
crates/pgt_completions/src/providers/columns.rs
crates/pgt_completions/src/providers/tables.rs
crates/pgt_completions/src/relevance.rs
crates/pgt_completions/src/sanitization.rs
crates/pgt_completions/src/test_helper.rs
crates/pgt_text_size/src/range.rs
crates/pgt_workspace/Cargo.toml
crates/pgt_workspace/src/features/completions.rs
crates/pgt_workspace/src/workspace.rs
crates/pgt_workspace/src/workspace/server.rs
crates/pgt_workspace/src/workspace/server/document.rs
postgrestools.jsonc

So far, we were relying on complete tree-sitter trees for autocompletion.
This works fine if you type the first letter of a node, say:
`select * from u|` 
Now, the `u` is considered a table node, and we can look for tables.
But this PR makes it such that we can also request completions if we haven't typed the `u` yet.
It does so by checking whether the tree is valid and, if not, injecting a token to fix the tree-sitter tree.
Additionally, in the case of `select * from |`, the workspace would consider the cursor to be outside the statement. I added a little offset so the cursor still matches a statement if it's 2 characters after the last token.

feat: request autocompletion without typing a letter

---

.github/workflows/release.yml
cliff.toml

- only generates the changelog for the version that is currently released 
- (I think) I fixed the deploy docs on release issue by allowing all tags to push to `github-pages `
- makes the template a bit nicer. example from the latest release:
A collection of language tools and a Language Server Protocol (LSP) implementation for Postgres, focusing on developer experience and reliable SQL tooling.
- Annotations (#331)
- Request autocompletion without typing a letter (#310)
- Make sure range is correct for eof deletions (#311)
- Properly trim statement (#313)
- Downgrade tunners (#318)
- Parse unions (#329)
- C-style comments (#332)
- Parser (#322)
- Simplify parser ? (#330)
- Add zed installation instructions (#315)

fix: release changelog

---

crates/pgt_workspace/src/configuration.rs

fixes #319 until we have versioned docs setup by
- preferring node_modules schema if available
- uses `latest` if the CLI does not have a version set (`0.0.0`)
- uses `VERSION` if a version is set

fix: dont point to 404 in config schema

---

crates/pgt_statement_splitter/src/lib.rs
crates/pgt_statement_splitter/src/parser.rs
crates/pgt_statement_splitter/src/parser/common.rs

fix: plpglsql cmds

---

crates/pgt_completions/benches/sanitization.rs
crates/pgt_completions/src/complete.rs
crates/pgt_completions/src/item.rs
crates/pgt_completions/src/providers/mod.rs
crates/pgt_completions/src/providers/schemas.rs
crates/pgt_completions/src/relevance.rs
crates/pgt_completions/src/sanitization.rs
crates/pgt_completions/src/test_helper.rs
crates/pgt_lsp/src/handlers/completions.rs
crates/pgt_schema_cache/src/lib.rs
crates/pgt_schema_cache/src/schemas.rs

Adds basic support for schema autocompletion.
The scoring algorithm still needs a lot of tweaking…

feat: autocomplete schemas

---

crates/pgt_workspace/src/workspace/server/change.rs

tried to reproduce a bug but I think this was already fixed. still, lets keep the test.

chore: test for typing comments

---

crates/pgt_typecheck/src/lib.rs
crates/pgt_typecheck/tests/diagnostics.rs
crates/pgt_workspace/src/workspace/server.rs

this pr reports database errors back when running the type-checker. they are reported as `WorkspaceError` and abort the diagnostics pull. the idea is that the user directly sees what's wrong instead of just waiting for 10s to see only the syntax errors and then wondering why the performance is so bad.
fixes #344

fix: report db connection errors

---

.github/workflows/pull_request.yml
Cargo.toml
crates/pgt_completions/benches/sanitization.rs
crates/pgt_completions/src/providers/columns.rs
crates/pgt_completions/src/providers/schemas.rs
crates/pgt_completions/src/sanitization.rs
crates/pgt_workspace/src/features/completions.rs

ran `lint-fix` and also added this into the CI so that we make sure all auto fixes are applied

chore: ensure auto fixes are applied 

---

crates/pgt_workspace/src/workspace/server/parsed_document.rs
crates/pgt_workspace/src/workspace/server/sql_function.rs

turns out I was so focused on the rewrite of that layer that I forgot to add even a single test for the sql fn body extraction 😢
fixes #342

fix: extract sql fn body properly

---

.github/workflows/release.yml

this causes ci to fail because it's always true: https://github.com/supabase-community/postgres-language-server/actions/runs/14575132494/job/40879545415?pr=359

fix: if clause in workflow file

---

crates/pgt_lsp/src/capabilities.rs

If `' '` triggers completions, `','` probably shouldn't.

fix(completions): remove , as trigger char

---

crates/pgt_completions/src/providers/columns.rs
crates/pgt_completions/src/sanitization.rs

Fixes three things:
1. Sanitizes the SQL when the cursor is on a `.` 
2. Fixes an issue where the processed SQL was cut off if the cursor was in the middle of the SQL
3. Removes an additional space that wasn't necessary

fix(completions): cursor on dot, other issues

---

.github/workflows/release.yml
crates/pgt_workspace/src/workspace/server/change.rs

the previous solution was only working if there are no statements. this has the same effect but also works if there are statements in the file.
fixes #343

fix: properly parse when there is no affected

---

crates/pgt_completions/src/builder.rs
crates/pgt_completions/src/context.rs
crates/pgt_completions/src/item.rs
crates/pgt_completions/src/providers/columns.rs
crates/pgt_completions/src/providers/functions.rs
crates/pgt_completions/src/providers/helper.rs
crates/pgt_completions/src/providers/mod.rs
crates/pgt_completions/src/providers/schemas.rs
crates/pgt_completions/src/providers/tables.rs
crates/pgt_lsp/src/handlers/completions.rs

yayy
https://github.com/user-attachments/assets/4711f5a6-fa9b-425e-9e75-7b4a06e4f6a0

feat(completions): insert schema name when selecting non-public tables

---

.github/workflows/pull_request.yml
Cargo.toml
crates/pgt_completions/src/providers/helper.rs
crates/pgt_completions/src/sanitization.rs
crates/pgt_completions/src/test_helper.rs
crates/pgt_workspace/src/workspace/server/change.rs
crates/pgt_workspace/src/workspace/server/document.rs
crates/pgt_workspace/src/workspace/server/parsed_document.rs
justfile
rust-toolchain.toml

- pin the rust toolchain to the version we use for the workspace
- reuse `just` commands in CI
- add steps where we print the versions of the tools used in CI
- install `sqlx-cli` with `just install-tools` and `just upgrade-tools` 
- remove `bun install` from `just upgrade-tools` 
- fixed all issues from clippy
the `rust-toolchain.toml` file was weird – it complained for the longest time that `cargo fmt` wasn't available with the 1.86.0 version, but now it just works. Seems to be just buggy sometimes

chore: align ci with local dev

---

crates/pgt_completions/src/builder.rs
crates/pgt_statement_splitter/src/lib.rs
crates/pgt_statement_splitter/src/parser/common.rs

looks like we can assume that it's always a statement if there's a comma before the newlines? 
```sql
select
email,
from
auth.users;
```
Note that this doesn't fix [this one](https://github.com/supabase-community/postgres-language-server/issues/372) – it's apparently not a splitter-problem, the file is correclty parsed as a single statement

fix?(splitter): allow newlines after commas

---

crates/pgt_statement_splitter/src/lib.rs
crates/pgt_statement_splitter/src/parser/common.rs

fix: properly parse trigger with instead of

---

crates/pgt_completions/src/context.rs
crates/pgt_completions/src/providers/columns.rs
crates/pgt_completions/src/providers/helper.rs
crates/pgt_completions/src/providers/schemas.rs
crates/pgt_completions/src/providers/tables.rs
crates/pgt_completions/src/relevance/filtering.rs
crates/pgt_completions/src/relevance/scoring.rs
crates/pgt_completions/src/test_helper.rs

Recognizes table aliases and only suggestings columns matching the aliased table.
Adds support for join clauses.

feat(completions): respect table aliases, complete in JOINs

---

crates/pgt_completions/src/context.rs
crates/pgt_completions/src/providers/columns.rs
crates/pgt_completions/src/relevance/filtering.rs
crates/pgt_completions/src/relevance/scoring.rs

Before, we were only completing columns in a JOIN in a "Binary Expression".
But for TreeSitter to recognize a Binary Expression, we need an `=` sign. 
So this wouldn't complete, since there's no `=` sign:
`select * from users u join posts p on u.{}` 
Now, we're checking for the `ON` node, and completing columns if we're after it.
Note: Multiple joins are each individual join clauses with their own separate ON nodes, so there's no intereference:
```sql
select * 
from 
users u
join posts p on u.id = post.user_id -- join clause 1
join {} -- join clause 2
```
We won't autocompete a column, since there's no ON node in join cluase 2 🥳

fix(completions): complete right columns right after JOIN ON

---

crates/pgt_workspace/src/workspace.rs
crates/pgt_workspace/src/workspace/server/change.rs

multiple changes at once happen during search and replace operations. 
Right now, we are handling each individually, one after another. this breaks starting at the second change because the range of each change is always related to the original state, not the previous. after fiddling with the `apply_change` method I figured this solution is the easiest. it expects that all changes are ordered properly, but afaik that's reasonable. if not and we receive bug reports, we can simply sort them. 
EDIT: ahh I need to handle the deletions case too! ✅

fix: properly handle multiple changes at once

---

Cargo.lock
crates/pgt_completions/Cargo.toml
crates/pgt_completions/src/providers/columns.rs
crates/pgt_completions/src/relevance/scoring.rs

This makes it such that we rank higher the `portfolio_settings` column if we type "sett" – before, it didn't get any boost.

fix(completions): use fuzzy matching for user input

---

crates/pgt_completions/src/relevance/filtering.rs

If we have `select * {}`, we shouldn't provide suggestions. It's annoying if you just want to write `from` 💩
If we have `select *, {}`, on the other hand, we should.

fix: do not complete right after asterisk

---

crates/pgt_completions/src/providers/columns.rs
crates/pgt_completions/src/providers/functions.rs
crates/pgt_completions/src/providers/helper.rs
crates/pgt_completions/src/providers/tables.rs

Given a query
```sql
select 
email, id
from
auth.users u
join auth.identities i on {}
```
if you pick `user_id` from the list, it will fill in `i.user_id` now.

feat(completions): fill in alias for columns in join clauses

---

biome.jsonc
crates/pgt_configuration/src/lib.rs
crates/pgt_lsp/src/server.rs
crates/pgt_lsp/src/session.rs
crates/pgt_workspace/src/workspace/server.rs

It enables passing workspace settings via the workspace/didChangeConfiguration notification. This in turn enables the client to specify settings dynamically, rather than being limited to configuration files. This is _a_ solution to #302. See example usage (with lspconfig) here: https://github.com/willruggiano/neovim.drv/commit/9aa06ad7c889ed7b14d35ab34264e757d5ad1a7e.
There is none. The payload of this handler is currently ignored.
The configuration received by the handler is merged with the fs configuration.

feat: allow configuration through workspace/didChangeConfiguration

---

crates/pgt_completions/src/context.rs
crates/pgt_completions/src/providers/columns.rs
crates/pgt_completions/src/providers/triggers.rs
crates/pgt_completions/src/relevance/scoring.rs
crates/pgt_completions/src/test_helper.rs
crates/pgt_treesitter_queries/src/queries/columns.rs
crates/pgt_treesitter_queries/src/queries/mod.rs
crates/pgt_treesitter_queries/src/queries/select_columns.rs

before, it would just suggest `aud` over and over.
https://github.com/user-attachments/assets/c0ec1d55-1844-42d4-b356-289819f258b9

feat(completions): lower priority of already mentioned columns in SELECT

---

crates/pgt_lsp/tests/server.rs
crates/pgt_workspace/src/workspace/server/change.rs

this should *finally* fix batched changes.
i was super confused every time i worked on this because it seemed like whatever i did, somehow something did not work. Turns out, we cannot rely on lsp clients to send batched changes consistently. this now fixes it by
1. sorting changes starting with the last
2. applying them starting from the last
3. not changing the ranges in any way
had to delete another test that has faulty data, but i am very sure that the three test cases cover both neovim and vscode behavior.
will push out a patch release once this is merged and hope the reports are not popping up again.

fix: batched changes

---

crates/pgt_configuration/src/analyser/linter/rules.rs
crates/pgt_workspace/src/workspace/server/analyser.rs
xtask/codegen/src/generate_configuration.rs

The `disabled_rules` were always empty – and I need them for the suppressions :)

fix(analyser): recognize disabled rules

---

crates/pgt_lsp/tests/server.rs
crates/pgt_query_ext/src/diagnostics.rs
crates/pgt_query_ext/src/lib.rs
crates/pgt_workspace/src/workspace/server.rs
crates/pgt_workspace/src/workspace/server/document.rs
crates/pgt_workspace/src/workspace/server/function_utils.rs
crates/pgt_workspace/src/workspace/server/pg_query.rs
crates/pgt_workspace/src/workspace/server/sql_function.rs
test.sql

feat: plpgsql syntax errors

---

crates/pgt_lexer/src/lexer.rs
crates/pgt_lexer/src/lib.rs
crates/pgt_lexer_codegen/src/syntax_kind.rs
crates/pgt_tokenizer/src/lib.rs
crates/pgt_tokenizer/src/snapshots/pgt_tokenizer__tests__named_param_at.snap
crates/pgt_tokenizer/src/snapshots/pgt_tokenizer__tests__named_param_colon_identifier.snap
crates/pgt_tokenizer/src/snapshots/pgt_tokenizer__tests__named_param_colon_raw.snap
crates/pgt_tokenizer/src/snapshots/pgt_tokenizer__tests__named_param_colon_string.snap
crates/pgt_tokenizer/src/token.rs

adds support for named parameters in tokenizer + lexer
for now, we support
- `@name` (sqlc)
- `:name`, `:'name'` and `:"name"` (psql)
closes #455
closes #456

feat: add support for named params

---

crates/pgt_lsp/src/handlers/text_document.rs
crates/pgt_lsp/src/utils.rs
crates/pgt_lsp/tests/server.rs
crates/pgt_statement_splitter/src/lib.rs
crates/pgt_statement_splitter/src/splitter/common.rs

fixes a crash in the splitter when the last char is a closing parentheses.

fix: splitter crash

---

crates/pgt_diagnostics_categories/src/categories.rs
docs/codegen/src/rules_index.rs
docs/codegen/src/rules_sources.rs
docs/rule_sources.md
docs/rules.md
xtask/codegen/src/generate_new_analyser_rule.rs

we'll have to deploy to see if this actually works – using `mike serve` apparently doesn't deploy the local `docs/` directory, but uses a git branch.

docs: fix links to rules

---

.sqlx/query-3ebf3d74eb9d0448d675882c7f8a23f1440c250590de976c5c46c5edf6746faf.json
crates/pgt_schema_cache/src/extensions.rs
crates/pgt_schema_cache/src/lib.rs
crates/pgt_schema_cache/src/queries/extensions.sql
crates/pgt_schema_cache/src/schema_cache.rs

as per pr title.
this is in preparation for introducing plpgsql_check support.

chore: add extensions to schema cache

---

crates/pgt_tokenizer/src/lib.rs
crates/pgt_tokenizer/src/snapshots/pgt_tokenizer__tests__named_param_dollar_raw.snap
crates/pgt_tokenizer/src/token.rs
crates/pgt_workspace/src/workspace/server.rs

closes #474 
from https://github.com/supabase-community/postgres-language-server/issues/454#issuecomment-3177986456

fix: add support for named param type `$name`

---

Cargo.lock
crates/pgt_plpgsql_check/src/lib.rs
crates/pgt_workspace/Cargo.toml
crates/pgt_workspace/src/workspace/server.tests.rs
crates/pgt_workspace/src/workspace/server/pg_query.rs

fixes #489
see issue comment for details

fix: ignore false positive

---

crates/pgt_configuration/src/lib.rs
crates/pgt_configuration/src/plpgsql_check.rs
crates/pgt_configuration/src/typecheck.rs
crates/pgt_workspace/src/settings.rs
crates/pgt_workspace/src/workspace/server.rs
crates/pgt_workspace/src/workspace/server.tests.rs
docs/schema.json
packages/@postgrestools/backend-jsonrpc/src/workspace.ts

while writing the configuration docs I realised that we are inconsistent in our settings. this pr adds `enabled` to `typecheck` as well as a new `plpgsql_check` settings. 
and adds another level of nesting to the async scope in `pull_diagnostics` ✨

feat: disable plpgsql-check in settings

---

crates/pgt_statement_splitter/src/lib.rs
crates/pgt_statement_splitter/src/splitter.rs
crates/pgt_statement_splitter/src/splitter/common.rs
crates/pgt_statement_splitter/src/splitter/dml.rs
crates/pgt_workspace/src/workspace/server.tests.rs

fix: statement splitter

---

crates/pgt_statement_splitter/src/lib.rs
crates/pgt_statement_splitter/src/splitter/common.rs

https://github.com/supabase-community/postgres-language-server/issues/135#issuecomment-3261229882

fix: revoke create splitter

---

crates/pgt_lexer/src/lexer.rs
crates/pgt_lexer_codegen/src/syntax_kind.rs
crates/pgt_tokenizer/src/lib.rs
crates/pgt_tokenizer/src/snapshots/pgt_tokenizer__tests__graphile_named_param.snap
crates/pgt_workspace/src/workspace/server/pg_query.rs

we were blindly converting named parameters to positional parameters. but the latter is only valid as a literal, and not as an identifier.
statements like
```sql
grant usage on schema public, app_public, app_hidden to :DB_ROLE;
```
are not valid when converted to
```sql
grant usage on schema public, app_public, app_hidden to $1;
```
i went a bit back and forth on this and decided the easiest way to fix this is to convert to identifiers like `a` if the previous non-trivia token is one of a set list of tokens. We will probably have a bunch of edge cases here but fixing them should be as easy as adding a keyword to the list.
now, we convert to
```sql
grant usage on schema public, app_public, app_hidden to a;
```
closes #510

fix: context-aware named param conversion

---

crates/pgt_completions/src/providers/functions.rs
crates/pgt_completions/src/providers/helper.rs
crates/pgt_completions/src/providers/tables.rs
crates/pgt_completions/src/relevance/filtering.rs
crates/pgt_completions/src/relevance/scoring.rs
crates/pgt_completions/src/sanitization.rs

- `select "auth"."| ;` will now correctly expand to `"auth"."uid"()` 
- `select "auth"."|" ;` as well
-  `select "auth".|` expands to `"auth".uid()` 
also: before, if there were quotes around a schema, we wouldn't find the possible tables/functions. now we do 🥳

feat(completions): correctly infer (quoted) schema for tables & functions

---

.github/workflows/publish.reusable.yml

`npm view` was checking the wrong package names – we need e.g. `@postgrestools/cli-aarch64-apple-darwin`

fix: npm package name checks

---

.sqlx/query-aced4382cedbfc359bb1c1ab71cf2472fa8afc0b24bf02ee1bfdfdbf111acfc8.json
crates/pgt_lexer/src/lexed.rs
crates/pgt_statement_splitter/src/lib.rs
crates/pgt_statement_splitter/src/splitter.rs

Splitter Context: If we expect a following keyword, but the next token is EOF, we'd push the expectation error onto the EOF token.
That EOF token is the last token in the `kind` vector, so `i == kind.len() - 1`, so `self.start[i+1]` would error:
To solve this case, we'll push the expectation error on the last token before EOF.

fix: do not push expectation errors to EOF
